global using Serilog;
global using Mapster;
global using Grpc.Core;
global using Utils.REPO;
global using Google.Protobuf.WellKnownTypes;
global using Microsoft.EntityFrameworkCore;
global using ClientService.Entities.Repo;
global using ClientService.Entities.Data;
global using ClientService.Entities.Models;